name: Test and lint
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup python
        run: uv python install
      - name: install project
        run: uv sync --locked --all-extras --dev
      - name: check license compatibility
        run: uv run licensecheck -0 --ignore-packages nvidia-* --requirements-paths pyproject.toml
      - name: ruff
        run: uv run ruff check
      - name: ty
        run: uv run ty check
      - name: pytest
        run: uv run pytest -vvv
